Group as array; putting in order main.
profcomff/preparation-timetable-data pull request #44
Opened 2023-07-24 15:19 UTC by SergeyZamyatin1

## Изменения
Теперь пары добавляются с массивом групп. Изменен скрипт ручного запуска.

## Реализации
Сам парсинг не поменялся. Дабавились только функции, склеивающие одинаковые пары для разных групп.

## Детали
Сначала пары полученные после парсинга разбиваются на болки с одинаоквым временем. Заитем в каждом блоке происходит склейка одинаковых пар для разных групп. 

## Check-List
- [ x] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить black и isort?

***P.S. Проставьте x в квадратные скобки в нужных пунктах. Example: [x]***

2023-07-24 15:28 UTC, grigoriev-semyon requested changes

2023-07-24 15:28 UTC, grigoriev-semyon commented on README.md
> +Сперва нужно отредактировать файл ````T.py````. Параметр at - токен авторизации в тестовую БД. Затем указать параметры соеднинения (host, database ...) для взятия данных
почему at? почему не по другому назвал?

2023-07-24 15:28 UTC, grigoriev-semyon commented on README.md
> +5. Setuptools;
а зачем вообще этот список если есть req's в сетапе? ты ж как либу это будешь ставить

2023-07-24 15:28 UTC, grigoriev-semyon commented on profcomff_parse_lib/database/id_instead_name.py
> +    # lessons["group"] = new_groups
комменты в помойку

2023-07-24 15:28 UTC, grigoriev-semyon commented on profcomff_parse_lib/database/id_instead_name.py
> +    # lessons["group"] = new_groups
комменты в помойку

2023-07-24 15:28 UTC, grigoriev-semyon commented on profcomff_parse_lib/timetable/core/parse_timetable.py
> +        html = instead_request(course, stream, group, conn)
комменты в помойку

2023-07-24 15:28 UTC, grigoriev-semyon commented on main.py
> +import T
что импортируется - непонятно
T - обычно имя дженерика а так оно не используется

2023-07-24 15:28 UTC, grigoriev-semyon commented on profcomff_parse_lib/__init__.py
> +           "all_to_array", "completion", "to_id", "calc_date", "delete_lessons", "add_lessons"]
мне точно нужно это все для работы?

2023-07-24 15:28 UTC, grigoriev-semyon commented on profcomff_parse_lib/database/groups_to_array.py
> +    res.reset_index(drop= True , inplace= True )
индент

2023-07-24 15:28 UTC, grigoriev-semyon commented on profcomff_parse_lib/database/groups_to_array.py
> +    while L > 0:
почему большая буква? это не тип

2023-07-24 15:53 UTC, SergeyZamyatin1 commented on profcomff_parse_lib/__init__.py
> +           "all_to_array", "completion", "to_id", "calc_date", "delete_lessons", "add_lessons"]
да

2023-07-28 13:56 UTC, grigoriev-semyon approved these changes

2023-07-28 13:57 UTC, merged